### ISSUE TITLE
Custom ami and overrideBootstrapCommand problem. Nodes faile to create

### ISSUE THREAD

**Issue by AqsaMemon** [gitpod-io/gitpod-eks-guide#44]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-2

managedNodeGroups:
  - name: ide
    instanceType: m6i.xlarge
    minSize: 2
    maxSize: 3
    disableIMDSv1: false

    volumeSize: 100
    volumeType: gp3
    volumeIOPS: 6000
    volumeThroughput: 500
    ebsOptimized: true

    privateNetworking: true
    ami: ami-0ad574da759c55c17

    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-1: "owned"
      
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh cluster-1
```
cluster.yaml file is working fine until I add overridebootstrap command. I am using eksctl version 0.84.0. Cluster is being created but nodes fail to create. Please help me with this. Thanks
